### ISSUE TITLE
Incompatible units in Foundation settings

### ISSUE THREAD

**Issue by trevorthornton** [NCSU-Libraries/ncsulib_foundation#194]
When we update [our Rails gem] (https://github.ncsu.edu/ncsu-libraries/ncsul_web-rails) with updated files from this repo there is one line that causes problems, and it gets fixed in our version then un-fixed when we update from here. The line is:
https://github.com/NCSU-Libraries/ncsulib_foundation/blob/master/scss/foundation/_settings.scss#L1149

And the fix is to change this:
$topbar-height: 68px;
to this:
$topbar-height: rem-calc(68);

For some reason doing it the first way throws an "Incompatible units" error when using Foundation 5.5, and doing the second way fixes the problem. I think they may have fixed it in Foundation - see this:
https://github.com/zurb/foundation/issues/6122

**Comment by erikncsu** [comment]
I changed the setting from px to rem-calc. Is that enough to fix it in the short term?

**Comment by trevorthornton** [comment]
That's the whole fix - that one little line breaks a whole site. I had fixed it in our gem, but Kevin just updated the files and it got un-fixed. Now it should stay fixed when we update. Thanks!
